version = 0.1
[default.deploy.parameters]
stack_name = "chatgpt-slack-bot"
resolve_s3 = false
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18dxk0fa350bx"
s3_prefix = "chatgpt-slack-bot"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
