AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chatgpt-slack-bot

  Sample SAM Template for chatgpt-slack-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  ChatGptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chatgpt-bot/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Environment:
        Variables:
          SLACK_BOT_TOKEN: 'aiueo'
          OPENAI_API_KEY: 'aiueo'