AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chatgpt-slack-bot

  Sample SAM Template for chatgpt-slack-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    # Tracing: Active

Resources:
  ChatGptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chatgpt-bot/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          SLACK_BOT_TOKEN: '{{resolve:secretsmanager:chatgptbot_secret:SecretString:SLACK_BOT_TOKEN}}'
          OPENAI_API_KEY: '{{resolve:secretsmanager:chatgptbot_secret:SecretString:OPENAI_API_KEY}}'